---
- hosts: localhost
  connection: local
  gather_facts: no


  # vars_files:
  #   - "vars/creds.json"

  roles:
    - role: "avinetworks.avisdk"

  tasks:


    # - name: Debug
    #   debug:
    #     msg: "{{ avi_credentials }}"
    #   tags:
    #     - debug

    - name: create an empty file if it doesn't exist
      file:
        path: "{{ zone }}SignedIn.csv"
        state: touch

    - name: create an empty file if it doesn't exist
      file:
        path: "{{ zone }}NotSignedIn.csv"
        state: touch

    - name: Gather Avi Users
      avi_api_session:
        avi_credentials: "{{ avi_credentials }}"
        api_version: "{{ avi_credentials.api_version }}"
        http_method: get
        timeout: 300
        path: useractivity
        tenant: "{{ tenant_ref | default('admin') }}"
        params:
          page_size: -1
      register: statusUseractivity

    # - name: Debug
    #   debug:
    #     msg: "{{ statusUseractivity.obj.results }}"
    #   tags:
    #     - debug

    - name: Append users in the list except admin
      set_fact:
        userList: "{{ (userList | default([])) + [item] }}"
      loop: "{{ statusUseractivity.obj.results }}"
      loop_control:
       label: "{{ item.name }}"
      when: item.name != "admin"

    - name: Append users in the list who did sign in
      set_fact:
        userListSignedIn: "{{ (userListSignedIn | default([])) + [item.name + ';True' ] }}"
      loop: "{{ userList }}"
      loop_control:
       label: "{{ item.name }}"
      when: item.last_login_timestamp is defined
      tags:
        - debug

    - name: Append users in the list who didn't sign in
      set_fact:
        userListNotSignedIn: "{{ (userListNotSignedIn | default([])) + [item.name + ';False' ] }}"
      loop: "{{ userList }}"
      loop_control:
       label: "{{ item.name }}"
      when: item.last_login_timestamp is not defined
      tags:
        - debug

    - name: Dump to file User who signed in
      lineinfile:
        line: "{{ item }}"
        path: "{{ zone }}SignedIn.csv"
      loop: "{{ userListSignedIn }}"

    - name: Dump to file User who did not sign in
      lineinfile:
        line: "{{ item }}"
        path: "{{ zone }}NotSignedIn.csv"
      loop: "{{ userListNotSignedIn }}"
